messages:
  select: "§aPainting selected."
  place: "§aPainting placed."
  
  cancel: "§cSelection canceled."
  list: "§cAvailable paintings: §6ALBAN, AZTEC, AZTEC2, BOMB, BURNINGSKULL, BUST, COURBET, CREEBET, DONKEYKONG, FIGHTERS, GRAHAM, KEBAB, MATCH, PIGSCENE, PLANT, POINTER, POOL, SEA, SKELETON, SKULL_AND_ROSES, STAGE, SUNSET, VOID, WANDERER, WASTELAND, WITHER "
  
  place-error: "§cThat painting is too big."
  cancel-error: "§cYou have not made a selection."
  
  no-painting: "§cYou must have a painting in your hand."
  invalid-painting: "§cSorry, that painting §e%p§c does not exist."
  
  non-player: "Error: This command can only be run by a player."
  